import "reflect-metadata";
import {UsersService} from "../services/users-service";
import {AuthService} from "../services/auth-service";
import {LikeService} from "../services/like-service";
import {JwtService} from "../application/jwt-service";
import {SessionsService} from "../services/sessions-service";
import {BlogsService} from "../services/blogs-service";
import {PostsService} from "../services/posts-service";
import {CommentsService} from "../services/comments-service";
import {DataBase} from "../repositories/dataBase";
import {QueryRepository} from "../repositories/query-repository";
import {container} from "./inversify.config";

export const db = container.get<DataBase>(DataBase);
export const queryRepository = container.get<QueryRepository>(QueryRepository);
export const usersService = container.get<UsersService>(UsersService);
export const authService = container.get<AuthService>(AuthService);
export const likeService = container.get<LikeService>(LikeService);
export const jwtService = container.get<JwtService>(JwtService);
export const sessionsService = container.get<SessionsService>(SessionsService);
export const commentsService = container.get<CommentsService>(CommentsService);
export const postsService = container.get<PostsService>(PostsService);
export const blogsService = container.get<BlogsService>(BlogsService);