import "reflect-metadata";
import {Container} from "inversify";
import {DataBase} from "../repositories/dataBase";
import {QueryRepository} from "../repositories/query-repository";
import {UsersRepository} from "../repositories/users-repository";
import {ReactionsRepository} from "../repositories/reactions-repository";
import {RefreshTokensMetaRepository} from "../repositories/refresh-tokens-meta-repository";
import {BlogsRepository} from "../repositories/blogs-repository";
import {PostsRepository} from "../repositories/posts-repository";
import {CommentsRepository} from "../repositories/comments-repository";
import {EmailAdapter} from "../adapters/email-adapter";
import {EmailManager} from "../managers/email-manager";
import {UsersService} from "../services/users-service";
import {AuthService} from "../services/auth-service";
import {LikeService} from "../services/like-service";
import {JwtService} from "../application/jwt-service";
import {SessionsService} from "../services/sessions-service";
import {CommentsService} from "../services/comments-service";
import {PostsService} from "../services/posts-service";
import {BlogsService} from "../services/blogs-service";

export const container = new Container();
container.bind<DataBase>(DataBase).to(DataBase);
container.bind<QueryRepository>(QueryRepository).to(QueryRepository);
container.bind<UsersRepository>(UsersRepository).to(UsersRepository);
container.bind<ReactionsRepository>(ReactionsRepository).to(ReactionsRepository);
container.bind<RefreshTokensMetaRepository>(RefreshTokensMetaRepository).to(RefreshTokensMetaRepository);
container.bind<BlogsRepository>(BlogsRepository).to(BlogsRepository);
container.bind<PostsRepository>(PostsRepository).to(PostsRepository);
container.bind<CommentsRepository>(CommentsRepository).to(CommentsRepository);
container.bind<EmailAdapter>(EmailAdapter).to(EmailAdapter);
container.bind<EmailManager>(EmailManager).to(EmailManager);
container.bind<UsersService>(UsersService).to(UsersService);
container.bind<AuthService>(AuthService).to(AuthService);
container.bind<LikeService>(LikeService).to(LikeService);
container.bind<JwtService>(JwtService).to(JwtService);
container.bind<SessionsService>(SessionsService).to(SessionsService);
container.bind<CommentsService>(CommentsService).to(CommentsService);
container.bind<PostsService>(PostsService).to(PostsService);
container.bind<BlogsService>(BlogsService).to(BlogsService);