import {UsersRepository} from "./repositories/users-repository";
import {UsersService} from "./services/users-service";
import {AuthService} from "./services/auth-service";
import {EmailAdapter} from "./adapters/email-adapter";
import {EmailManager} from "./managers/email-manager";
import {ReactionsRepository} from "./repositories/reactions-repository";
import {LikeService} from "./services/like-service";
import {RefreshTokensMetaRepository} from "./repositories/refresh-tokens-meta-repository";
import {JwtService} from "./application/jwt-service";
import {SessionsService} from "./services/sessions-service";
import {BlogsRepository} from "./repositories/blogs-repository";
import {BlogsService} from "./services/blogs-service";
import {PostsRepository} from "./repositories/posts-repository";
import {PostsService} from "./services/posts-service";
import {CommentsRepository} from "./repositories/comments-repository";
import {CommentsService} from "./services/comments-service";
import {DataBase} from "./repositories/dataBase";
import {settings} from "./config/settings";
import {QueryRepository} from "./repositories/query-repository";

export const db = new DataBase(settings.MONGO_URL)
export const queryRepository = new QueryRepository(db);
const usersRepository = new UsersRepository(db);
const reactionsRepository = new ReactionsRepository(db);
const refreshTokensMetaRepository = new RefreshTokensMetaRepository(db);
const blogsRepository = new BlogsRepository(db);
const postsRepository = new PostsRepository(db);
const commentsRepository = new CommentsRepository(db);
const emailAdapter = new EmailAdapter();
const emailManager = new EmailManager(emailAdapter);
export const usersService = new UsersService(usersRepository, refreshTokensMetaRepository);
export const authService = new AuthService(usersRepository, emailManager);
export const likeService = new LikeService(reactionsRepository);
export const jwtService = new JwtService(refreshTokensMetaRepository);
export const sessionsService = new SessionsService(refreshTokensMetaRepository);
export const commentsService = new CommentsService(commentsRepository);
export const postsService = new PostsService(postsRepository, commentsService, queryRepository);
export const blogsService = new BlogsService(blogsRepository, postsService);